name: Clear GoDaddy-Sucuri Cache (Manual)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cache-clear:
    name: Clear GoDaddy (Sucuri) WAF Cache
    runs-on: ubuntu-latest
    steps:
      - name: Send Cache Clear Request to Sucuri API
        run: |
          curl -X POST "https://waf.sucuri.net/api?v2" \
          -d "k=${{ secrets.GODADDY_API_KEY }}" \
          -d "s=${{ secrets.GODADDY_API_SECRET }}" \
          -d "a=clear_cache"