name: Clear Sucuri Cache

on:
  workflow_dispatch:

jobs:
  clear-cache:
    name: Clear Sucuri WAF Cache
    runs-on: ubuntu-latest
    steps:
      - name: Send cache clear request to Sucuri API
        run: |
          curl -X POST "https://waf.sucuri.net/api?v2" \
          -d "k=${{ secrets.SUCURI_API_KEY }}" \
          -d "s=${{ secrets.SUCURI_API_SECRET }}" \
          -d "a=clear_cache"