name: Deploy and Clear Cache (Full Process)

on:
  workflow_dispatch:

jobs:
  call-deploy-workflow:
    name: 1. Call Deploy Website Workflow
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  call-cache-workflow:
    name: 2. Call Clear GoDaddy-Sucuri Cache Workflow
    needs: call-deploy-workflow
    uses: ./.github/workflows/clear-cache.yml
    secrets: inherit